export const encodePathSegment = (value: string): string =>
    encodeURIComponent(value)

export const adminRoutes = {
    dashboard: '/',
    setup: '/setup',
    login: '/login',
    agents: '/agents',
    agentNew: '/agents/new',
    agentDetail: '/agents/:id',
    agent: (id: string): string => `/agents/${encodePathSegment(id)}`,
    runtimes: '/runtimes',
    runtimeDetail: '/runtimes/:id',
    runtime: (id: string): string => `/runtimes/${encodePathSegment(id)}`,
    chatSessions: '/chat-sessions',
    chatSessionDetail: '/chat-sessions/:id',
    chatSession: (id: string): string =>
        `/chat-sessions/${encodePathSegment(id)}`,
    sandboxes: '/sandboxes',
    sandboxNew: '/sandboxes/new',
    channels: '/channels',
    channelNew: '/channels/new',
    channelDetail: '/channels/:id',
    channel: (id: string): string => `/channels/${encodePathSegment(id)}`,
    modelProviders: '/model-providers',
    modelProviderKeys: '/model-providers/keys',
    modelProviderChannels: '/model-providers/channels',
    modelProviderModels: '/model-providers/models',
    modelProviderBuiltInPrices: '/model-providers/built-in-prices',
    infrastructure: '/infrastructure',
    clusters: '/infrastructure/clusters',
    clusterNew: '/infrastructure/clusters/new',
    clusterDetail: '/infrastructure/clusters/:id',
    cluster: (id: string): string =>
        `/infrastructure/clusters/${encodePathSegment(id)}`,
    sandboxAccounts: '/infrastructure/sandbox-accounts',
    sandboxAccountNew: '/infrastructure/sandbox-accounts/new',
    sandboxAccountDetail: '/infrastructure/sandbox-accounts/:slug',
    sandboxAccount: (slug: string): string =>
        `/infrastructure/sandbox-accounts/${encodePathSegment(slug)}`,
    selfOwnedComputers: '/infrastructure/self-owned-computers',
    selfOwnedComputerMachines:
        '/infrastructure/self-owned-computers/machines',
    selfOwnedComputerClientPolicy:
        '/infrastructure/self-owned-computers/client-policy',
    sandboxCapacity: '/infrastructure/sandbox-capacity',
    accounts: '/accounts',
    accountUsers: '/accounts/users',
    accountUserDetail: '/accounts/users/:id',
    accountUser: (id: string): string =>
        `/accounts/users/${encodePathSegment(id)}`,
    growth: '/growth',
    growthChannels: '/growth/channels',
    growthCampaigns: '/growth/campaigns',
    growthLinks: '/growth/links',
    growthReport: '/growth/report',
    billing: '/billing',
    billingSubscriptions: '/billing/subscriptions',
    billingInvoices: '/billing/invoices',
    billingPayments: '/billing/payments',
    catalog: '/catalog',
    frameworkCatalog: '/catalog/frameworks',
    frameworkModels: '/catalog/frameworks/models',
    frameworkVersions: '/catalog/frameworks/versions',
    frameworkProvisioning: '/catalog/frameworks/provisioning',
    skillCatalogRoot: '/catalog/skills',
    skillCatalog: '/catalog/skills/catalog',
    skillSources: '/catalog/skills/sources',
    skillCategories: '/catalog/skills/categories',
    mcpRoot: '/catalog/mcp',
    mcpCatalog: '/catalog/mcp/catalog',
    mcpCatalogNew: '/catalog/mcp/catalog/new',
    mcpCatalogDetail: '/catalog/mcp/catalog/:id',
    mcpCatalogItem: (id: string): string =>
        `/catalog/mcp/catalog/${encodePathSegment(id)}`,
    mcpCategories: '/catalog/mcp/categories',
    platform: '/platform',
    platformAuthentication: '/platform/authentication',
    platformEmail: '/platform/email',
    notificationWebhooks: '/platform/notification-webhooks',
    notificationWebhookNew: '/platform/notification-webhooks/new',
    notificationWebhookDetail: '/platform/notification-webhooks/:id',
    notificationWebhook: (id: string): string =>
        `/platform/notification-webhooks/${encodePathSegment(id)}`,
    turnPolicies: '/platform/turn-policies',
    dataRetention: '/platform/data-retention',
    rollouts: '/platform/rollouts',
    rolloutExperiments: '/platform/rollouts/experiments',
    experimentNew: '/platform/rollouts/experiments/new',
    experimentDetail: '/platform/rollouts/experiments/:key',
    experiment: (key: string): string =>
        `/platform/rollouts/experiments/${encodePathSegment(key)}`,
    rolloutFeatureFlags: '/platform/rollouts/feature-flags'
} as const