import {
    AgentFramework,
    AgentModelConfig,
    AgentModelConfigSource,
    FrameworkInstallSource,
    codingAgentWorkspacePath,
    createObjectId,
    frameworkMcpSupport,
    mcpConfigFromExtras
} from '@manyfold/shared'
import {
    ConflictException,
    Inject,
    Injectable,
    Logger,
    NotFoundException,
    Optional,
    ServiceUnavailableException
} from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import { and, count, eq, isNull, sql } from 'drizzle-orm'
import {
    agents,
    agentRuntimes,
    runtimeHosts,
    type AgentRuntimeRow,
    type Database,
    type RuntimeHostRow,
    type SpritesAccount
} from '@manyfold/db'
import {
    createClient,
    SpritesError,
    type SpritesClient,
    type SpritesLogger
} from '@manyfold/sprites'
import { DRIZZLE } from '@/db/tokens'
import { SpritesAccountsService } from '@/modules/sprites-accounts/sprites-accounts.service'
import { ClaudeCodeBootstrap } from '@/modules/agents/bootstrap/claude-code'
import { CodexBootstrap } from '@/modules/agents/bootstrap/codex'
import { GeminiCliBootstrap } from '@/modules/agents/bootstrap/gemini'
import { HermesSpriteBootstrap } from '@/modules/agents/bootstrap/hermes-sprite'
import { OpenClawSpriteBootstrap } from '@/modules/agents/bootstrap/openclaw-sprite'
import { NarraNexusSpriteBootstrap } from '@/modules/agents/bootstrap/narranexus-sprite'
import {
    BootstrapError,
    type BootstrapContext
} from '@/modules/agents/bootstrap/framework-bootstrap'
import type {
    SpriteServiceBootstrap,
    SpriteServiceBootstrapResult
} from '@/modules/agents/bootstrap/sprite-framework-bootstrap'
import { defaultNetworkPolicy } from '@/modules/agents/orchestration/bootstrap-invariants'
import type { AgentProgressEmitter } from '@/modules/agents/orchestration/agent-orchestrator.service'
import { AgentRuntimesService } from '@/modules/agent-runtimes/agent-runtimes.service'
import { RuntimeAccessService } from '@/modules/runtime-access/runtime-access.service'
import { SandboxActiveDurationService } from '@/modules/agents/sandbox-active-duration/sandbox-active-duration.service'
import { RuntimeTokenService } from '@/modules/auth/runtime-token.service'
import {
    cliInstallChannelForDeployEnv,
    SpriteShellEnvService
} from '@/modules/agent-self/sprite-shell-env.service'
import { publicApiUrlWithApiPrefix } from '@/common/public-api-url'
import { resolveMfDeployEnv } from '@/common/deploy-env'
import { assertWorkspaceUsableOnSprite } from '@/modules/agents/workspace/workspace-preflight'
import { SpriteKeepAliveLeaseService } from '@/modules/agents/keep-alive/sprite-keepalive-lease.service'
import {
    McpConfigMaterializer,
    spriteScopeIo
} from '@/modules/agent-runtimes/mcp/mcp-config-materializer.service'
import {
    probeSandboxExec,
    type SandboxExecProbeResult
} from '@/modules/agent-runtimes/provisioning/sandbox-exec-health'

// How long a failed exec-readiness probe stays on a sandbox host as a diagnostic
// marker. Short enough that a recovered VM's record clears without an operator.
const SANDBOX_EXEC_COOLDOWN_MS = 10 * 60_000

export interface SpritesProvisionInput {
    userId: string
    framework: AgentFramework
    accountId: string | null
    // When set, attach to this existing standalone sandbox host instead of
    // provisioning a new VM. The account is taken from the host, not selected.
    attachHostId?: string | null
    isAdmin: boolean
    credentials: unknown
    emitter: AgentProgressEmitter
    agentId: string
    workspacePath?: string
    workspaceManaged?: boolean
    modelConfig?: AgentModelConfig | null
    // 'runtime-local' drives the credential-less bootstrap path (no platform
    // keys written, no key login, no paid verify). See BootstrapContext.
    modelConfigSource?: AgentModelConfigSource | null
    frameworkVersion?: string | null
    // Provenance of `frameworkVersion`; drives whether a failed install is fatal
    // or degrades to the framework's built-in default. See installFrameworkVersion.
    frameworkVersionSource?: FrameworkInstallSource
    // Repository a git-installed framework clones from, resolved with
    // `frameworkVersion` so the two cannot name different repos.
    frameworkRepo?: string | null
}

export interface SpritesProvisionOutput {
    runtime: AgentRuntimeRow
    account: SpritesAccount
    spritesClient: SpritesClient
    homeDir?: string
    /** sprite URL captured from a service-kind bootstrap, for `agent.ingressHost`. */
    endpointUrl?: string | null
    /** Tokens generated by a service-kind bootstrap (apiServerKey, gatewayToken). */
    generatedCredentials?: Record<string, string>
}

@Injectable()
export class SpritesProvisioner {
    private readonly log = new Logger(SpritesProvisioner.name)

    private readonly serviceBootstraps: ReadonlyMap<
        AgentFramework,
        SpriteServiceBootstrap
    >

    constructor(
        @Inject(DRIZZLE) private readonly db: Database,
        private readonly accounts: SpritesAccountsService,
        private readonly runtimes: AgentRuntimesService,
        private readonly claudeBootstrap: ClaudeCodeBootstrap,
        private readonly codexBootstrap: CodexBootstrap,
        private readonly geminiBootstrap: GeminiCliBootstrap,
        hermesSpriteBootstrap: HermesSpriteBootstrap,
        openclawSpriteBootstrap: OpenClawSpriteBootstrap,
        narraNexusSpriteBootstrap: NarraNexusSpriteBootstrap,
        private readonly runtimeAccess: RuntimeAccessService,
        private readonly config: ConfigService,
        private readonly shellEnv: SpriteShellEnvService,
        private readonly keepAliveLease: SpriteKeepAliveLeaseService,
        private readonly activeDuration: SandboxActiveDurationService,
        @Optional() private readonly runtimeToken?: RuntimeTokenService,
        @Optional() private readonly mcp?: McpConfigMaterializer
    ) {
        this.serviceBootstraps = new Map<
            AgentFramework,
            SpriteServiceBootstrap
        >([
            ['hermes', hermesSpriteBootstrap],
            ['openclaw', openclawSpriteBootstrap],
            ['narranexus', narraNexusSpriteBootstrap]
        ])
    }

    // Run a daemon (service-kind) bootstrap, degrading to the framework's
    // built-in version when we only *implicitly* asked for the newest upstream
    // release. Unlike a coding agent — where the sprite image already ships a
    // working CLI to fall back on — a daemon has nothing installed, so the only
    // way to honour "keep creating agents even when the newest release is
    // broken" is to re-run the bootstrap unpinned (openclaw dist-tag / hermes
    // main / narranexus NARRANEXUS_VERSION). An asked-for version (user dto /
    // admin pin) still fails loud.
    //
    // The retry is deliberately narrowed to the `<framework>-install` step, which
    // is the FIRST thing every daemon bootstrap does — before it writes config or
    // touches the Services API. Re-running after a later failure is not safe: the
    // service would already exist with the first attempt's generated tokens, and
    // `upsertService` alone does not propagate new env (that needs the
    // delete→upsert→start dance in `restart()`), so the sprite would keep running
    // token A while we persist token B.
    private async runServiceBootstrap(
        bootstrap: SpriteServiceBootstrap,
        ctx: BootstrapContext,
        credentials: unknown
    ): Promise<
        SpriteServiceBootstrapResult & { installedVersion: string | null }
    > {
        const requested = ctx.frameworkVersion ?? null
        try {
            const result = await bootstrap.run(ctx, credentials)
            return {
                ...result,
                installedVersion: requested?.replace(/^v/, '') ?? null
            }
        } catch (err) {
            const retryable =
                requested !== null &&
                ctx.frameworkVersionSource === 'latest' &&
                err instanceof BootstrapError &&
                err.step === `${bootstrap.framework}-install`
            if (!retryable) throw err
            ctx.logger.warn(`${bootstrap.framework}.install.latest.failed`, {
                spriteName: ctx.spriteName,
                requested,
                detail: (err as Error).message
            })
            // Version left null: we don't know what the fallback installed, and
            // guessing would put a wrong version on the runtime row. The existing
            // probe / sandbox detect fills it in.
            const result = await bootstrap.run(
                {
                    ...ctx,
                    frameworkVersion: null,
                    frameworkVersionSource: 'none'
                },
                credentials
            )
            return { ...result, installedVersion: null }
        }
    }

    // Host-level helpers (no agent): the shared shell-env block (MF_API_URL +
    // MF_DEPLOY_ENV, never a token) and the mf CLI. Shared by agent-create and
    // standalone-sandbox provisioning; idempotent, so it re-runs safely when an
    // agent later attaches. Best-effort — failures WARN, never throw.
    private async installHostSelfHelpers(args: {
        client: SpritesClient
        spriteName: string
        logger: SpritesLogger
    }): Promise<void> {
        try {
            const apiBaseUrl = this.config?.get<string>('PUBLIC_API_BASE_URL')
            const deployEnv = resolveMfDeployEnv(
                this.config?.get<string>('MF_DEPLOY_ENV')
            )
            // No-token shell env only: MF_API_URL + MF_DEPLOY_ENV don't depend
            // on any agents row. The per-agent identity token is injected
            // per-exec (chat) / per-session (terminal), never on the profile.
            if (this.shellEnv) {
                await this.shellEnv.write({
                    client: args.client,
                    spriteName: args.spriteName,
                    agentId: '',
                    apiBaseUrl: apiBaseUrl
                        ? publicApiUrlWithApiPrefix(apiBaseUrl)
                        : undefined,
                    deployEnv,
                    logger: args.logger
                })
            }
            if (!apiBaseUrl) {
                this.log.warn(
                    `PUBLIC_API_BASE_URL not configured; omitting MF_API_URL shell env on ${args.spriteName}`
                )
            }
            if (
                (deployEnv === 'local' || deployEnv === 'staging') &&
                this.shellEnv
            ) {
                await this.shellEnv.installCli({
                    client: args.client,
                    spriteName: args.spriteName,
                    channel: cliInstallChannelForDeployEnv(deployEnv),
                    logger: args.logger
                })
            }
        } catch (err) {
            this.log.warn(
                `host-self helpers install failed for ${args.spriteName}: ${(err as Error).message}`
            )
        }
    }

    // Best-effort read of the agent's stored per-scope MCP config. Returns {}
    // when the agents row isn't there yet (initial create) or on any error.
    private async loadStoredMcp(agentId: string): Promise<{
        mcp: Record<string, string>
        userId: string | null
        composioConnectionId: string | null
    }> {
        try {
            const [row] = await this.db
                .select({ userId: agents.userId, extras: agents.extras })
                .from(agents)
                .where(eq(agents.id, agentId))
                .limit(1)
            const extras = row?.extras as
                | { composioConnectionId?: string | null }
                | undefined
            return {
                mcp: mcpConfigFromExtras(row?.extras),
                userId: row?.userId ?? null,
                composioConnectionId: extras?.composioConnectionId ?? null
            }
        } catch {
            return { mcp: {}, userId: null, composioConnectionId: null }
        }
    }


    /**
     * Mint the agent's runtime identity token and inject it into the sprite's
     * managed shell-env block. Split out of provisioning because the mint writes
     * an agent_runtime_tokens row whose agent_id FK references agents.id — so it
     * MUST run AFTER the agents row is inserted, not during bootstrap.
     *
     * Fail-loud (§3.5 gate): when there is a reachable API URL the identity is
     * mandatory — a missing token service, a mint failure, or a shell-env-write
     * failure all throw so the caller rolls the half-provisioned runtime back
     * via teardownRuntime (never a tokenless agent in a gated env). Without an
     * API URL the token is inert (the agent falls back to `mf login`), so we
     * skip with a single WARN — preserving local/non-gated provisions.
     * Re-issues the whole NCA_* block, so it's idempotent over the no-token
     * block written during provisioning.
     */
    async installRuntimeIdentity(args: {
        userId: string
        agentId: string
        client: SpritesClient
        spriteName: string
        logger?: SpritesLogger
    }): Promise<void> {
        const apiBaseUrl = this.config?.get<string>('PUBLIC_API_BASE_URL')
        if (!apiBaseUrl) {
            this.log.warn(
                `skipping runtime identity for ${args.spriteName}: PUBLIC_API_BASE_URL not configured`
            )
            return
        }
        if (!this.runtimeToken)
            throw new Error(
                `runtime identity required for ${args.spriteName} (PUBLIC_API_BASE_URL is set) but RuntimeTokenService is not wired`
            )
        // Mint + encrypt-store the per-agent identity. It is injected per-exec
        // from the encrypted copy, NOT written to the shared sprite profile, so
        // co-resident agents on one VM keep distinct identities.
        await this.runtimeToken.mintRuntimeIdentity({
            userId: args.userId,
            agentId: args.agentId,
            runtimeKind: 'sprites'
        })
    }

    // Attach uses the sandbox's own account (the VM already lives there), not a
    // freshly-selected one. Validates ownership/kind/active + a published VM.
    private async resolveAttachAccount(
        userId: string,
        hostId: string
    ): Promise<SpritesAccount> {
        const host = await this.runtimes.findHostById(hostId)
        if (
            !host ||
            host.userId !== userId ||
            host.kind !== 'sandbox' ||
            host.status !== 'active' ||
            !host.accountId ||
            !host.spriteId
        )
            throw new NotFoundException({
                message: `sandbox ${hostId} not available`,
                code: 'SANDBOX_NOT_FOUND'
            })
        const account = await this.accounts.getById(host.accountId)
        if (!account)
            throw new NotFoundException({
                message: `sandbox ${hostId} account missing`,
                code: 'SANDBOX_NOT_FOUND'
            })
        return account
    }

    // Bring up the sprite VM that agent-create and standalone-sandbox share:
    // create the VM, hand the spriteId to the caller (so it persists it where it
    // belongs + flips its own created flag), then apply the default network
    // policy. createSprite throwing leaves onSpriteId uncalled; a setNetworkPolicy
    // throw runs after onSpriteId (so the caller knows the VM exists to clean up).
    private async createSpriteVm(args: {
        spritesClient: SpritesClient
        spriteName: string
        emitter?: AgentProgressEmitter
        onSpriteId: (spriteId: string | null) => Promise<void>
    }): Promise<string | null> {
        args.emitter?.step('creating_sprite')
        const sprite = await args.spritesClient.createSprite({
            name: args.spriteName
        })
        const spriteId = typeof sprite.id === 'string' ? sprite.id : null
        await args.onSpriteId(spriteId)
        args.emitter?.step('applying_network_policy')
        await args.spritesClient.setNetworkPolicy(
            args.spriteName,
            defaultNetworkPolicy()
        )
        return spriteId
    }

    // Bring up a standalone sandbox VM with no agent/runtime. sprite_id is
    // published LAST (after VM + policy + host helpers) so a concurrent attach
    // can't reuse a VM that failed mid-bring-up; reuse gates on sprite_id.
    async provisionSandbox(args: {
        hostId: string
        spriteName: string
        spritesClient: SpritesClient
    }): Promise<void> {
        let spriteCreated = false
        try {
            const spriteId = await this.createSpriteVm({
                spritesClient: args.spritesClient,
                spriteName: args.spriteName,
                onSpriteId: async () => {
                    spriteCreated = true
                }
            })
            await this.installHostSelfHelpers({
                client: args.spritesClient,
                spriteName: args.spriteName,
                logger: spritesLoggerFor(this.log)
            })
            await this.runtimes.setSandboxHostSprite(args.hostId, spriteId)
        } catch (err) {
            let spriteDeleted = true
            if (spriteCreated) {
                spriteDeleted = await this.deleteCreatedSprite(
                    args.spritesClient,
                    args.spriteName,
                    'sandbox sprite cleanup failed'
                )
            }
            if (spriteDeleted)
                await this.runtimes.deleteSandboxHost(args.hostId)
            else await this.runtimes.revokeSandboxHost(args.hostId)
            throw err
        }
    }

    async createStandaloneSandbox(args: {
        userId: string
        name?: string
        accountId: string | null
        isAdmin: boolean
    }): Promise<RuntimeHostRow> {
        const account = await this.accounts.selectForCreate({
            accountId: args.accountId ?? undefined,
            callerIsAdmin: args.isAdmin
        })
        const token = this.accounts.decryptToken(account)
        const spritesClient = createClient({
            token,
            accountSlug: account.slug,
            logger: spritesLoggerFor(this.log)
        })
        const host = await this.runtimeAccess.reserveStandaloneSandbox({
            userId: args.userId,
            name: args.name,
            accountId: account.id
        })
        if (!host.spriteName)
            throw new Error(
                `reserveStandaloneSandbox assigned no spriteName for ${host.id}`
            )
        await this.provisionSandbox({
            hostId: host.id,
            spriteName: host.spriteName,
            spritesClient
        })
        const refreshed = await this.runtimes.findHostById(host.id)
        return refreshed ?? host
    }

    // Test seam: the probe opens a real WebSocket, so provisioning tests
    // override this rather than stand up a sprite exec endpoint.
    protected async probeExec(
        client: SpritesClient,
        spriteName: string
    ): Promise<SandboxExecProbeResult> {
        return probeSandboxExec({
            client,
            spriteName,
            logger: spritesLoggerFor(this.log)
        })
    }

    // Record that a sandbox host failed an exec probe. Nothing consumes the
    // cooldown for placement any more (placement is explicit — see
    // reserveSpriteRuntime), so this is the diagnostic trail for a wedged VM.
    // Returns the cooldown deadline for the caller's log line.
    private async quarantineHost(
        hostId: string,
        detail: string
    ): Promise<Date> {
        const until = new Date(Date.now() + SANDBOX_EXEC_COOLDOWN_MS)
        await this.runtimes.markSandboxHostExecCooldown(hostId, until)
        this.log.warn(
            `sandbox host quarantined ${JSON.stringify({
                hostId,
                cooldownUntil: until.toISOString(),
                detail
            })}`
        )
        return until
    }

    /**
     * Reserve the runtime, then make sure the VM it landed on can actually run
     * an exec before bootstrap commits to it.
     *
     * Only an attach lands on a pre-existing VM, and that VM may have no liveness
     * signal at all — a sprite whose exec endpoint is chronically 502ing would
     * otherwise fail deep inside bootstrap. Probing first (with a no-op command,
     * so retrying it is side-effect free) turns that into a clean 503 plus a
     * quarantine record. There is no failover: the caller named one sandbox, and
     * silently placing the agent elsewhere would ignore what they asked for.
     *
     * A freshly created VM is not probed: its first exec is the bootstrap, and a
     * failure there deletes the VM instead of leaving it behind for the next
     * create.
     */
    private async reserveHealthyRuntime(args: {
        userId: string
        framework: AgentFramework
        accountId: string
        attachHostId?: string | null
        mountPath: string
        client: SpritesClient
    }): Promise<{
        runtimeId: string
        reserved: AgentRuntimeRow
        hostCreated: boolean
    }> {
        const runtimeId = createObjectId('agentRuntime')
        const { runtime, hostCreated } =
            await this.runtimeAccess.reserveSpriteRuntime({
                id: runtimeId,
                userId: args.userId,
                framework: args.framework,
                accountId: args.accountId,
                hostId: args.attachHostId ?? undefined,
                mountPath: args.mountPath,
                currentPhase: 'creating_sprite'
            })
        if (hostCreated || !runtime.hostId || !runtime.spriteName)
            return { runtimeId, reserved: runtime, hostCreated }

        let probe: SandboxExecProbeResult
        try {
            probe = await this.probeExec(args.client, runtime.spriteName)
        } catch (err) {
            await this.runtimes.delete(runtimeId)
            throw err
        }
        if (probe.ok) return { runtimeId, reserved: runtime, hostCreated }

        const detail = probe.detail ?? 'exec probe failed'
        this.log.warn(
            `sandbox host exec probe failed ${JSON.stringify({
                hostId: runtime.hostId,
                spriteName: runtime.spriteName,
                probeAttempts: probe.attempts,
                detail,
                action: 'attach-target-unhealthy'
            })}`
        )
        await this.quarantineHost(runtime.hostId, detail)
        await this.runtimes.delete(runtimeId)
        throw new ServiceUnavailableException({
            message: `sandbox is not accepting commands (${detail})`,
            code: 'SANDBOX_EXEC_UNAVAILABLE'
        })
    }

    async provisionRuntime(
        input: SpritesProvisionInput
    ): Promise<SpritesProvisionOutput> {
        const {
            userId,
            framework,
            accountId,
            isAdmin,
            credentials,
            emitter,
            agentId
        } = input

        emitter.step('selecting_account')
        const account = input.attachHostId
            ? await this.resolveAttachAccount(userId, input.attachHostId)
            : await this.accounts.selectForCreate({
                  accountId: accountId ?? undefined,
                  callerIsAdmin: isAdmin
              })
        const token = this.accounts.decryptToken(account)
        const spritesClient = createClient({
            token,
            accountSlug: account.slug,
            logger: spritesLoggerFor(this.log)
        })

        const workspacePath =
            input.workspacePath ?? codingAgentWorkspacePath('sprites', agentId)
        const workspaceManaged = input.workspaceManaged ?? true

        emitter.step('checking_quota')
        // reserveSpriteRuntime assigns the sandbox host (+ derives spriteName)
        // atomically under the per-user lock. hostCreated=false means we reused
        // an existing VM (co-resident framework) and must skip VM creation — and
        // must first prove that VM still answers an exec.
        const { runtimeId, reserved, hostCreated } =
            await this.reserveHealthyRuntime({
                userId,
                framework,
                accountId: account.id,
                attachHostId: input.attachHostId,
                mountPath: workspacePath,
                client: spritesClient
            })
        const spriteName = reserved.spriteName
        if (!spriteName)
            throw new Error(
                `reserveSpriteRuntime assigned no spriteName for ${runtimeId}`
            )

        let spriteCreated = false
        try {
            if (hostCreated) {
                await this.createSpriteVm({
                    spritesClient,
                    spriteName,
                    emitter,
                    onSpriteId: async (spriteId) => {
                        spriteCreated = true
                        await this.runtimes.applyStatusPatch(runtimeId, {
                            spriteId
                        })
                        // The sandbox host's sprite_id (the co-residence reuse
                        // gate) is published in finalizeReady, NOT here — the VM
                        // still has to pass bootstrap/identity, any of which can
                        // fail into the catch and delete the VM. Publishing now
                        // would let a concurrent create reuse a doomed VM.
                        await this.runtimes.setPhase(
                            runtimeId,
                            'applying_network_policy'
                        )
                    }
                })
            } else {
                // Reused VM: inherit its spriteId onto the new runtime row.
                await this.runtimes.applyStatusPatch(runtimeId, {
                    spriteId: reserved.spriteId
                })
            }

            await this.runtimes.setPhase(runtimeId, 'bootstrapping')
            emitter.step('bootstrapping')
            if (!workspaceManaged)
                await assertWorkspaceUsableOnSprite({
                    client: spritesClient,
                    spriteName,
                    workspacePath,
                    logger: spritesLoggerFor(this.log),
                    timeoutMs: 30_000
                })
            const bootstrapCtx: BootstrapContext = {
                agentId,
                runtimeId,
                userId,
                spriteName,
                mountPath: workspacePath,
                client: spritesClient,
                logger: spritesLoggerFor(this.log),
                execTimeoutMs: 60_000,
                modelConfig: input.modelConfig ?? null,
                modelConfigSource: input.modelConfigSource ?? null,
                frameworkVersion: input.frameworkVersion ?? null,
                frameworkVersionSource: input.frameworkVersionSource ?? 'none',
                frameworkRepo: input.frameworkRepo ?? null
            }
            let homeDir: string | undefined
            let endpointUrl: string | null | undefined
            let generatedCredentials: Record<string, string> | undefined
            let installedVersion: string | null = null
            const codingBootstrap =
                framework === 'claude-code'
                    ? this.claudeBootstrap
                    : framework === 'codex'
                      ? this.codexBootstrap
                      : framework === 'gemini-cli'
                        ? this.geminiBootstrap
                        : null
            if (codingBootstrap) {
                // Coding CLIs are npm-installed to the resolved version inside the
                // bootstrap; claude-code is a big package, so surface it as its own
                // step or `bootstrapping` sits over a minute and looks dead.
                emitter.step('installing_framework')
                const result = await codingBootstrap.run(
                    bootstrapCtx,
                    credentials
                )
                homeDir = result.homeDir
                installedVersion = result.frameworkVersion ?? null
            } else {
                const serviceBootstrap = this.serviceBootstraps.get(framework)
                if (!serviceBootstrap)
                    throw new Error(
                        `sprites runtime does not support framework ${framework}`
                    )
                // Heartbeat steps for service-kind bootstraps — install can
                // take ~3 min and starting the service another ~10s. Without
                // these the UI sits on `bootstrapping` and looks dead.
                emitter.step('installing_framework')
                const result = await this.runServiceBootstrap(
                    serviceBootstrap,
                    bootstrapCtx,
                    credentials
                )
                emitter.step('starting_service')
                homeDir = result.homeDir
                endpointUrl = result.endpointUrl
                generatedCredentials = result.generatedCredentials
                installedVersion = result.installedVersion
            }

            await this.installHostSelfHelpers({
                client: spritesClient,
                spriteName,
                logger: spritesLoggerFor(this.log)
            })

            if (homeDir || installedVersion) {
                await this.runtimes.applyProvisioningPatch(runtimeId, {
                    ...(homeDir ? { homeDir } : {}),
                    ...(installedVersion
                        ? {
                              frameworkVersion: installedVersion,
                              frameworkVersionCheckedAt: new Date()
                          }
                        : {})
                })
            }

            // Project the agent's stored MCP config onto the fresh sprite. Empty
            // on first create (nothing set yet); on a re-provision/rebuild this
            // restores servers the user configured earlier. Best-effort inside.
            if (homeDir && this.mcp && frameworkMcpSupport(framework)) {
                const stored = await this.loadStoredMcp(agentId)
                await this.mcp.materialize({
                    io: spriteScopeIo(
                        spritesClient,
                        spriteName,
                        spritesLoggerFor(this.log)
                    ),
                    targetLabel: spriteName,
                    framework,
                    homeDir,
                    workspacePath,
                    mcp: stored.mcp,
                    userId: stored.userId ?? '',
                    composioConnectionId: stored.composioConnectionId
                })
            }

            const refreshed = await this.runtimes.findById(runtimeId)
            if (!refreshed) throw new Error('runtime row disappeared')
            return {
                runtime: refreshed,
                account,
                spritesClient,
                homeDir,
                endpointUrl,
                generatedCredentials
            }
        } catch (err) {
            // A reused host survives this rollback (it still owns its other
            // runtimes), so a transient sprite failure here would otherwise
            // leave it active and first in line for the next create — the exact
            // loop the readiness probe exists to break. Quarantine it too; the
            // probe only covers the window before bootstrap.
            if (!hostCreated && reserved.hostId && isTransientSpriteError(err))
                await this.quarantineHost(
                    reserved.hostId,
                    'exec endpoint unavailable before connection opened'
                ).catch((markErr: unknown) =>
                    this.log.warn(
                        `sandbox host quarantine failed for ${reserved.hostId} class=${errorClass(markErr)}`
                    )
                )
            let preserveHostForCleanupRetry = false
            if (spriteCreated) {
                const spriteDeleted = await this.deleteCreatedSprite(
                    spritesClient,
                    spriteName,
                    'sprite cleanup failed'
                )
                preserveHostForCleanupRetry =
                    !spriteDeleted && hostCreated && !!reserved.hostId
                if (preserveHostForCleanupRetry && reserved.hostId) {
                    await this.runtimes.revokeSandboxHost(reserved.hostId)
                }
            }
            await this.runtimes.delete(runtimeId)
            // Drop the freshly-created sandbox host if we own it and it's now
            // empty (a reused VM keeps living for its other runtimes).
            if (
                hostCreated &&
                reserved.hostId &&
                !preserveHostForCleanupRetry
            ) {
                if (!(await this.runtimes.hostHasRuntimes(reserved.hostId)))
                    await this.runtimes.deleteSandboxHost(reserved.hostId)
            }
            throw err
        }
    }

    async finalizeReady(runtimeId: string, now: Date): Promise<void> {
        await this.runtimes.applyStatusPatch(runtimeId, {
            status: 'ready',
            startedAt: now,
            lastBootstrappedAt: now,
            failureReason: null
        })
        await this.runtimes.setPhase(runtimeId, null)
        // Publish the sandbox host for co-residence reuse only now that the first
        // runtime is fully provisioned — past every failure point that deletes
        // the VM. reserveSpriteRuntime gates reuse on sprite_id, so until this a
        // concurrent create can't reuse a half-provisioned / soon-torn-down VM.
        // Idempotent for reused hosts (sprite_id already set).
        const runtime = await this.runtimes.findById(runtimeId)
        if (runtime?.hostId && runtime.spriteId)
            await this.runtimes.setSandboxHostSprite(
                runtime.hostId,
                runtime.spriteId
            )
    }

    /**
     * Wake the sprite-side framework service. Lease-free: the keep-alive
     * lease is owned by the `keep_alive_enabled` column, not by traffic, so
     * a wake never re-instates a lease the user turned off. The one
     * exception: when this call actually cold-started the service, the
     * pre-start cleanup just cleared any existing tasks, so an enabled
     * runtime must re-establish its lease in the same call.
     *
     * Called from the chat activity path so that an agent stopped via
     * `stopSprite` — or a sprite that suspended naturally — comes back
     * to life on the next chat turn. Stop is handled directly by
     * `SpriteKeepAliveLeaseService.stopAndRelease` from `AgentsService`.
     *
     * No-op for exec-kind frameworks (claude/codex/gemini-cli) and for any
     * agent without an accountId yet (still provisioning).
     */
    async wakeSpriteRuntime(runtime: AgentRuntimeRow): Promise<void> {
        const { started } =
            await this.keepAliveLease.ensureServiceRunning(runtime)
        if (started && runtime.keepAliveEnabled) {
            await this.keepAliveLease.ensureLease(runtime)
        }
    }

    /**
     * Toggle the keep-alive switch. The flag write is the commitment (enable
     * is quota-gated and atomic in `enableKeepAlive`); sprite-side ops are
     * best-effort — the reconcile passes converge a degraded toggle within
     * ~60s, so the API returns the committed flag even when sprite ops fail.
     */
    async setKeepAlive(
        userId: string,
        runtime: AgentRuntimeRow,
        enabled: boolean
    ): Promise<AgentRuntimeRow> {
        if (enabled) {
            if (!runtime.hostId)
                throw new Error(
                    `runtime ${runtime.id} has no hostId for keep-alive`
                )
            await this.runtimeAccess.enableKeepAlive({
                userId,
                runtimeId: runtime.id,
                hostId: runtime.hostId
            })
        } else {
            await this.runtimes.setKeepAliveEnabled(runtime.id, false)
        }
        const refetched = await this.runtimes.findById(runtime.id)
        if (!refetched) throw new Error('runtime row disappeared')
        try {
            if (enabled) {
                await this.keepAliveLease.ensureServiceRunning(refetched)
                await this.keepAliveLease.ensureLease(refetched)
            } else {
                await this.keepAliveLease.releaseLease(refetched, 'user-toggle')
            }
        } catch (err) {
            this.log.warn(
                `keep-alive ${enabled ? 'enable' : 'disable'} sprite ops degraded for ${runtime.id}: ${(err as Error).message}`
            )
        }
        return refetched
    }

    // Delete a runtime + its agents. When this empties the host, the default
    // PRESERVES the VM (sets emptied_at so the reaper deletes it after the idle
    // window) so a deleted agent leaves a reusable sandbox. reapImmediatelyIfEmpty
    // restores the eager delete for explicit runtime deletes + failed creates.
    async teardownRuntime(
        runtime: AgentRuntimeRow,
        opts?: { reapImmediatelyIfEmpty?: boolean }
    ): Promise<void> {
        const reapImmediately = opts?.reapImmediatelyIfEmpty ?? false
        // Settle any open active-duration interval before this teardown clears
        // the host's running status or deletes the row, so the final running
        // seconds are credited and no stale watermark survives. If the host stays
        // occupied + running, the next status sample re-opens it (≤3s gap).
        if (runtime.hostId)
            await this.activeDuration.settleHostNotRunning(
                runtime.hostId,
                runtime.userId,
                new Date()
            )
        // Serialize against reserveSpriteRuntime (same per-user advisory lock,
        // namespace 0) so a concurrent attach can't reuse this host between the
        // emptiness check and the marking/deletion.
        const action = await this.db.transaction(async (tx) => {
            await tx.execute(
                sql`select pg_advisory_xact_lock(hashtextextended(${runtime.userId}, 0))`
            )
            await tx.delete(agents).where(eq(agents.runtimeId, runtime.id))
            await tx
                .delete(agentRuntimes)
                .where(eq(agentRuntimes.id, runtime.id))
            if (!runtime.hostId) return 'keep' as const
            const [row] = await tx
                .select({ value: count() })
                .from(agentRuntimes)
                .where(eq(agentRuntimes.hostId, runtime.hostId))
            if (Number(row?.value ?? 0) > 0) return 'keep' as const
            if (!reapImmediately) {
                // Preserve the now-empty VM. Start the reaper clock and clear any
                // stale running status so it stops counting toward concurrency.
                await tx
                    .update(runtimeHosts)
                    .set({
                        emptiedAt: new Date(),
                        spriteStatus: null,
                        activeAccrualSince: null,
                        updatedAt: new Date()
                    })
                    .where(
                        and(
                            eq(runtimeHosts.id, runtime.hostId),
                            eq(runtimeHosts.kind, 'sandbox'),
                            isNull(runtimeHosts.emptiedAt)
                        )
                    )
                return 'keep' as const
            }
            // Eager delete: mark non-reusable (reuse gates on status='active')
            // but keep the row as the retry record until the VM is confirmed gone.
            await tx
                .update(runtimeHosts)
                .set({ status: 'revoked', updatedAt: new Date() })
                .where(
                    and(
                        eq(runtimeHosts.id, runtime.hostId),
                        eq(runtimeHosts.kind, 'sandbox')
                    )
                )
            return 'reap' as const
        })
        if (action !== 'reap') return

        if (runtime.accountId && runtime.spriteName) {
            const account = await this.accounts.getById(runtime.accountId)
            if (account) {
                const token = this.accounts.decryptToken(account)
                const client = createClient({
                    token,
                    accountSlug: account.slug,
                    logger: spritesLoggerFor(this.log)
                })
                // A non-not_found failure throws BEFORE the host row is removed,
                // leaving it 'revoked' (non-reusable) as the retry record.
                await client.deleteSprite(runtime.spriteName).catch((err) => {
                    if (!isSpritesNotFound(err)) throw err
                })
            }
        }
        // VM gone (or confirmed absent) → drop the now-revoked host row.
        if (runtime.hostId)
            await this.runtimes.deleteSandboxHost(runtime.hostId)
    }

    // Explicit user/admin sandbox delete. Rejects while any agent/runtime is
    // still on the host (delete those first); empty → delete the VM + host row.
    // Serialized on the per-user lock so it can't race an attach.
    async deleteSandbox(args: {
        userId: string
        hostId: string
    }): Promise<void> {
        const host = await this.runtimes.findHostById(args.hostId)
        if (!host || host.userId !== args.userId || host.kind !== 'sandbox')
            throw new NotFoundException({
                message: `sandbox ${args.hostId} not found`,
                code: 'SANDBOX_NOT_FOUND'
            })
        const revoked = await this.db.transaction(async (tx) => {
            await tx.execute(
                sql`select pg_advisory_xact_lock(hashtextextended(${args.userId}, 0))`
            )
            const [row] = await tx
                .select({ value: count() })
                .from(agentRuntimes)
                .where(eq(agentRuntimes.hostId, args.hostId))
            if (Number(row?.value ?? 0) > 0)
                throw new ConflictException({
                    message: 'sandbox still has agents; delete them first',
                    code: 'SANDBOX_NOT_EMPTY'
                })
            const updated = await tx
                .update(runtimeHosts)
                .set({ status: 'revoked', updatedAt: new Date() })
                .where(
                    and(
                        eq(runtimeHosts.id, args.hostId),
                        eq(runtimeHosts.kind, 'sandbox')
                    )
                )
                .returning({ id: runtimeHosts.id })
            return updated.length > 0
        })
        if (!revoked) return
        // Credit the final running interval before the host row is deleted (the
        // ledger row outlives the host so the user's monthly rollup is intact).
        await this.activeDuration.settleHostNotRunning(
            args.hostId,
            host.userId,
            new Date()
        )

        if (host.accountId && host.spriteName) {
            const account = await this.accounts.getById(host.accountId)
            if (account) {
                const token = this.accounts.decryptToken(account)
                const client = createClient({
                    token,
                    accountSlug: account.slug,
                    logger: spritesLoggerFor(this.log)
                })
                await client.deleteSprite(host.spriteName).catch((err) => {
                    if (!isSpritesNotFound(err)) throw err
                })
            }
        }
        await this.runtimes.deleteSandboxHost(args.hostId)
    }

    private async deleteCreatedSprite(
        client: SpritesClient,
        spriteName: string,
        warningPrefix: string
    ): Promise<boolean> {
        try {
            await client.deleteSprite(spriteName).catch((err) => {
                if (!isSpritesNotFound(err)) throw err
            })
            return true
        } catch (cleanupErr) {
            const msg =
                cleanupErr instanceof Error
                    ? cleanupErr.message
                    : String(cleanupErr)
            this.log.warn(`${warningPrefix} for ${spriteName}: ${msg}`)
            return false
        }
    }
}

const isSpritesNotFound = (err: unknown): boolean =>
    err instanceof SpritesError && err.code === 'not_found'

// Only a transient sprite failure says anything about host health. Auth, quota,
// not_found and a framework's own non-zero exit are the agent's problem, not the
// VM's, and must not take a working host out of rotation.
const isTransientSpriteError = (err: unknown): boolean =>
    err instanceof SpritesError &&
    err.code === 'transient' &&
    err.execPhase === 'pre_open'

const errorClass = (err: unknown): string =>
    err instanceof SpritesError
        ? `SpritesError:${err.code}`
        : err instanceof Error && err.name
          ? err.name
          : typeof err

const spritesLoggerFor = (log: Logger): SpritesLogger => ({
    debug: (m: string, meta?: Record<string, unknown>) =>
        log.debug?.(`[sprites] ${m} ${JSON.stringify(meta ?? {})}`),
    info: (m: string, meta?: Record<string, unknown>) =>
        log.log(`[sprites] ${m} ${JSON.stringify(meta ?? {})}`),
    warn: (m: string, meta?: Record<string, unknown>) =>
        log.warn(`[sprites] ${m} ${JSON.stringify(meta ?? {})}`),
    error: (m: string, meta?: Record<string, unknown>) =>
        log.error(`[sprites] ${m} ${JSON.stringify(meta ?? {})}`)
})
