import { HERMES_DASHBOARD_PORT, HERMES_PORT } from '@/modules/agents/bootstrap/hermes-shared'

// Route matcher for the hermes front proxy, written as a self-contained JS
// function SOURCE so the exact code that unit tests exercise (via
// `new Function`) is the code rendered into the .mjs that runs on the sprite
// — no tested-table-vs-shipped-string drift.
//
// Contract: returns 'gateway' | 'dashboard' | 'html'.
//   gateway   → 127.0.0.1:8642 (hermes gateway; chat /v1 + /v1/health)
//   dashboard → 127.0.0.1:9119 pass-through (static assets + /api/*, which
//               hermes gates with its own session token)
//   html      → dashboard, but ONLY with a valid ?token= or the
//               mf_dashboard_token cookie the proxy grants after a tokened
//               visit — in loopback mode hermes injects the session token
//               into index.html for ANY requester, so every path that can
//               serve HTML must be gated here. Unknown paths deliberately
//               fall into this bucket (default deny).
export const HERMES_PROXY_MATCHER_SRC = `(pathname) => {
    if (pathname === '/v1' || pathname.startsWith('/v1/')) return 'gateway'
    if (
        pathname.startsWith('/assets/') ||
        pathname.startsWith('/fonts/') ||
        pathname.startsWith('/fonts-terminal/') ||
        pathname === '/favicon.ico' ||
        pathname === '/api' ||
        pathname.startsWith('/api/')
    )
        return 'dashboard'
    return 'html'
}`

// Upstream header rewrite, extracted as SOURCE for the same no-drift reason
// as the matcher. Host is always pinned to loopback (the dashboard's
// host-header middleware 400s non-local hosts). Origin is route-dependent:
// the dashboard's WS guard rejects any non-loopback Origin BEFORE accepting
// the upgrade — a browser sends the public sprite origin, so every dashboard
// WS (chat /api/ws, terminal /api/pty, events) died as a 1006 — while the
// GATEWAY 403s any request that carries an Origin header at all (anti-browser
// guard, verified live 2026-07-03). So dashboard-bound requests get Origin
// pinned to loopback and gateway-bound requests pass it through untouched.
export const HERMES_PROXY_UPSTREAM_HEADERS_SRC = `(headers, port, route) => ({
    ...headers,
    host: \`127.0.0.1:\${port}\`,
    ...(route === 'gateway' ? {} : { origin: \`http://127.0.0.1:\${port}\` })
})`

// Credential extraction for HTML-serving routes, extracted as SOURCE like the
// matcher. The dashboard SPA drops ?token= from the address bar on its first
// client-side navigation, so a refresh or deep link would 401 forever with a
// query-only gate. The proxy therefore grants an mf_dashboard_token cookie on
// every successful tokened visit and accepts it as an equal credential; the
// query param wins when both are present so a freshly minted URL always
// re-syncs a stale cookie. Value comparison stays timing-safe in the script.
export const HERMES_PROXY_CREDENTIAL_SRC = `(url, cookieHeader) => {
    const query = new URL(url, 'http://sprite').searchParams.get('token') ?? ''
    if (query) return { value: query, via: 'query' }
    for (const part of (cookieHeader ?? '').split(';')) {
        const eq = part.indexOf('=')
        if (eq === -1) continue
        if (part.slice(0, eq).trim() !== 'mf_dashboard_token') continue
        const value = part.slice(eq + 1).trim()
        if (value) return { value, via: 'cookie' }
    }
    return { value: '', via: 'none' }
}`

// The front proxy that owns the sprite's single public http_port when the
// hermes dashboard is enabled. Node stdlib only — the sprite image ships
// node 22 and the script must run with zero install steps.
export const renderHermesFrontProxyScript = (): string => `// Generated by Manyfold — do not edit. Front proxy for the hermes dashboard:
// splits the sprite's single public port between the gateway (chat) and the
// dashboard web server, and gates every HTML-serving path behind ?token= or
// the session cookie it grants (hermes loopback mode injects its session
// token into index.html for any caller).
import http from 'node:http'
import net from 'node:net'
import { timingSafeEqual } from 'node:crypto'

const PROXY_PORT = Number(process.env.MF_PROXY_PORT ?? 18642)
const GATEWAY_PORT = Number(process.env.MF_GATEWAY_PORT ?? ${HERMES_PORT})
const DASHBOARD_PORT = Number(process.env.MF_DASHBOARD_PORT ?? ${HERMES_DASHBOARD_PORT})
const TOKEN = process.env.MF_DASHBOARD_TOKEN ?? ''

const decideRoute = ${HERMES_PROXY_MATCHER_SRC}

// The SPA drops ?token= from the address bar on its first client-side
// navigation, so refreshes/deep links authenticate via the cookie granted
// below. Sliding 30-day window, re-set on every authenticated HTML load.
const credential = ${HERMES_PROXY_CREDENTIAL_SRC}

const tokenMatches = (supplied) => {
    if (!TOKEN || !supplied) return false
    const a = Buffer.from(supplied)
    const b = Buffer.from(TOKEN)
    return a.length === b.length && timingSafeEqual(a, b)
}

const grantCookie = () =>
    \`mf_dashboard_token=\${TOKEN}; Path=/; Max-Age=2592000; Secure; HttpOnly; SameSite=Lax\`

const portFor = (route) => (route === 'gateway' ? GATEWAY_PORT : DASHBOARD_PORT)

const deny = (res) => {
    res.writeHead(401, { 'content-type': 'text/plain; charset=utf-8' })
    res.end('401 — open this dashboard from Manyfold (missing or invalid token)')
}

// Host pinned to loopback (dashboard 400s non-local hosts). Origin pinned to
// loopback only for dashboard-bound requests (its WS guard rejects public
// Origins pre-accept); the gateway 403s ANY request carrying an Origin, so
// gateway-bound requests keep theirs untouched.
const upstreamHeaders = ${HERMES_PROXY_UPSTREAM_HEADERS_SRC}

const server = http.createServer((req, res) => {
    const route = decideRoute(new URL(req.url ?? '/', 'http://sprite').pathname)
    let sessionCookie = null
    if (route === 'html') {
        const cred = credential(req.url ?? '/', req.headers.cookie)
        if (!tokenMatches(cred.value)) return deny(res)
        sessionCookie = grantCookie()
    }
    const port = portFor(route)
    const upstream = http.request(
        {
            host: '127.0.0.1',
            port,
            path: req.url,
            method: req.method,
            headers: upstreamHeaders(req.headers, port, route)
        },
        (up) => {
            const destroyDownstream = () => {
                if (res.writableEnded || res.destroyed) return
                res.destroy()
            }
            // Once response headers have crossed the proxy there is no 502 left
            // to send. If that upstream response dies, close its partial
            // downstream twin instead of leaving the caller hung forever.
            up.on('aborted', destroyDownstream)
            up.on('error', destroyDownstream)
            const headers = { ...up.headers }
            if (sessionCookie) {
                const prior = headers['set-cookie']
                headers['set-cookie'] = [
                    ...(Array.isArray(prior) ? prior : prior ? [prior] : []),
                    sessionCookie
                ]
            }
            res.writeHead(up.statusCode ?? 502, headers)
            up.pipe(res)
        }
    )
    upstream.on('error', () => {
        // A caller that already went away cannot be told anything: writing the
        // 502 into a dead response only manufactures an error of our own.
        if (res.writableEnded || res.destroyed) return
        if (res.headersSent) return res.destroy()
        res.writeHead(502)
        res.end('upstream unavailable')
    })
    // A cancelled chat turn arrives here as nothing but this close, and piping
    // alone never propagates it — the proxy-to-gateway request stays
    // established and hermes keeps generating into a socket nobody reads.
    // Seen on staging [2026-08-14]: a cancelled turn still finished its call
    // (in=13620 out=334), then ran a tool and opened another. writableFinished
    // is what separates a response that completed from a caller that left
    // early, so normal turns keep their upstream untouched.
    res.on('close', () => {
        if (res.writableFinished) return
        upstream.destroy()
    })
    req.pipe(upstream)
})

server.on('upgrade', (req, socket, head) => {
    const route = decideRoute(new URL(req.url ?? '/', 'http://sprite').pathname)
    if (
        route === 'html' &&
        !tokenMatches(credential(req.url ?? '/', req.headers.cookie).value)
    ) {
        socket.destroy()
        return
    }
    const port = portFor(route)
    const upstream = net.connect(port, '127.0.0.1', () => {
        const headerLines = Object.entries(
            upstreamHeaders(req.headers, port, route)
        )
            .map(([k, v]) => \`\${k}: \${Array.isArray(v) ? v.join(', ') : v}\`)
            .join('\\r\\n')
        upstream.write(
            \`\${req.method} \${req.url} HTTP/1.1\\r\\n\${headerLines}\\r\\n\\r\\n\`
        )
        if (head?.length) upstream.write(head)
        socket.pipe(upstream)
        upstream.pipe(socket)
    })
    upstream.on('error', () => socket.destroy())
    socket.on('error', () => upstream.destroy())
})

server.listen(PROXY_PORT, '0.0.0.0')
`