import type {
    BootstrapContext,
    BootstrapResult
} from '@/modules/agents/bootstrap/framework-bootstrap'

export interface SpriteServiceBootstrapResult extends BootstrapResult {
    /** Name registered on the sprite's Services API. */
    serviceName: string
    /** Port the service binds to; routed via the sprite URL. */
    httpPort?: number
    /** Public sprite URL captured during provisioning. */
    endpointUrl?: string | null
    /** Tokens generated by the bootstrap (apiServerKey, gatewayToken, …) — persisted as agent credentials by the orchestrator. */
    generatedCredentials?: Record<string, string>
    /** Inherited from BootstrapResult; daemon bootstraps leave it unset (the
     * provisioner records the tag it asked for, or null after a fallback). */
    frameworkVersion?: string | null
}

/**
 * Service-kind sprite bootstrap. For frameworks that run as long-lived daemons
 * (Hermes, OpenClaw, NarraNexus) rather than per-request exec invocations
 * (claude-code, codex, gemini-cli).
 *
 * The bootstrap is responsible for:
 *   1. Installing the framework binary inside the sprite
 *   2. Writing any config files into the sprite home dir
 *   3. Delegating start.sh to `SpriteKeepAliveLeaseService.install()`, which
 *      writes a plain exec wrapper — keep-alive is a separate, column-gated
 *      lease loop, not part of the start script
 *   4. PUT-ing a service definition (via `client.upsertService`)
 *   5. Starting the service (via `client.startService`)
 *   6. Returning the service name, port, sprite URL, and any generated tokens
 */
export interface SpriteServiceBootstrap {
    readonly framework: 'hermes' | 'openclaw' | 'narranexus'
    run(
        ctx: BootstrapContext,
        credentials: unknown
    ): Promise<SpriteServiceBootstrapResult>
    // Re-apply the service env (incl. ctx.envText) and bounce the service WITHOUT
    // reinstalling. Sprite env only propagates via delete→upsert→start (see
    // SpritesClient.upsertService caveat), so this runs that dance.
    restart(ctx: BootstrapContext, credentials: unknown): Promise<void>
}
