import type { Context } from '@opentelemetry/api'
import type { AnyValue, LogAttributes } from '@opentelemetry/api-logs'
import type { LogRecordProcessor, SdkLogRecord } from '@opentelemetry/sdk-logs'

// Frozen compatibility names, not a registry to extend for each new event.
// Unknown keys remain typed/queryable inside custom instead of growing columns.
export const FLATTENED_LOG_ATTRIBUTE_KEYS = [
    'accountId',
    'accountSlug',
    'acquired',
    'action',
    'activeTurnsAtStart',
    'activeTurnsRemaining',
    'adoptCount',
    'afterDays',
    'agentAgeMs',
    'agentCount',
    'agentId',
    'ageSec',
    'assistantMessageId',
    'attachments',
    'attempts',
    'aws.s3.bucket',
    'blocking',
    'blocks',
    'brand',
    'broughtUp',
    'callerAgentId',
    'cancelled',
    'canonical',
    'canonicalSet',
    'capped',
    'cause',
    'causeVia',
    'channelId',
    'chars',
    'chatSessionId',
    'cliVersion',
    'cloud.region',
    'command',
    'consumedLines',
    'context',
    'contextRefs',
    'cooldownMs',
    'count',
    'currentGeneration',
    'cursored',
    'daemonId',
    'db.namespace',
    'db.operation.name',
    'db.query.text',
    'db.response.status_code',
    'db.system.name',
    'deletedMessageCount',
    'detail',
    'dispatchedGeneration',
    'dispatches',
    'dispatchInflight',
    'dispatchMs',
    'dryRun',
    'durationMs',
    'effectiveEffort',
    'error',
    'error.type',
    'errorClass',
    'errorCode',
    'errorKind',
    'errorMessage',
    'estimatedRows',
    'event',
    'eventLoopDelayMaxMs',
    'eventLoopDelayP99Ms',
    'eventLoopUtilization',
    'eventType',
    'execToFirstStdoutMs',
    'exitCode',
    'failed',
    'failureClass',
    'fallbackReason',
    'firstTokenMs',
    'framework',
    'frameworkSessionRef',
    'from',
    'fromSeq',
    'generation',
    'handedOffTurns',
    'handoffOutcome',
    'heapUsedMb',
    'holderId',
    'homeBytes',
    'hostId',
    'http.request.method',
    'http.request.method_original',
    'http.response.status_code',
    'http.route',
    'inflight',
    'keepAliveDisabled',
    'key',
    'kind',
    'leaseMs',
    'lifetimeMs',
    'limitHours',
    'local',
    'measuredVia',
    'messageId',
    'method',
    'minimumCliVersion',
    'mode',
    'model',
    'nca.agent_id',
    'nca.duration_ms',
    'nca.error_class',
    'nca.error_message',
    'nca.event',
    'nca.fetch_timeout_ms',
    'nca.first_token_ms',
    'nca.framework',
    'nca.headers_ms',
    'nca.headers_timeout_ms',
    'nca.last_activity_age_ms',
    'nca.max_duration_ms',
    'nca.outcome',
    'nca.preflight_attempts',
    'nca.preflight_budget_ms',
    'nca.provider_calls',
    'nca.session_id',
    'nca.stream_idle_timeout_ms',
    'nca.timeout_kind',
    'nca.tokens_emitted',
    'nca.upstream_status',
    'nca.upstream_status_text',
    'network.peer.address',
    'network.peer.port',
    'openForMs',
    'origin',
    'outcome',
    'peakDispatchInflight',
    'peakInflight',
    'peakRecoveryInflight',
    'pendingChars',
    'phase',
    'polls',
    'previousState',
    'probes',
    'protocol',
    'provider',
    'providerEventId',
    'purged',
    'queuedMs',
    'reason',
    'recoveredLines',
    'recoveryInflight',
    'refId',
    'remainingTasks',
    'requestedEffort',
    'resolvedGeneration',
    'resumed',
    'retentionDays',
    'retryable',
    'retryInMs',
    'rows',
    'rowsCleared',
    'rpc.method',
    'rpc.service',
    'rpc.system',
    'rssMb',
    'runnerKind',
    'runtime',
    'runtimeId',
    'runtimeKind',
    'scanned',
    'scope',
    'scopeKey',
    'senderId',
    'server.address',
    'server.port',
    'sessionCreated',
    'sessionId',
    'setupMs',
    'shape',
    'shutdownOutcome',
    'sideEffect',
    'signal',
    'sinceFirstErrorMs',
    'softCap',
    'source',
    'sourceFile',
    'span_id',
    'spriteExecSessionId',
    'spriteName',
    'stack',
    'state',
    'stoppedHosts',
    'targetAgentId',
    'targetKind',
    'taskId',
    'timeoutMs',
    'to',
    'tokensIn',
    'tokensOut',
    'totalBytes',
    'trace_id',
    'trigger',
    'turnDrainOutcome',
    'turnPhase',
    'unresolvedHosts',
    'uploads',
    'url.full',
    'url.path',
    'url.query',
    'url.scheme',
    'usedHours',
    'user_agent.original',
    'userId',
    'via',
    'vmUsedBytes',
    'warm',
    'warmLimit',
    'workspaceBytes',
    'workspaceEnsureMs',
    'workspacePreflight'
] as const

const flattenedKeys = new Set<string>(FLATTENED_LOG_ATTRIBUTE_KEYS)
const isScalar = (value: AnyValue): boolean =>
    typeof value === 'string' ||
    typeof value === 'number' ||
    typeof value === 'boolean'
const isFlatValue = (value: AnyValue): boolean =>
    isScalar(value) || (Array.isArray(value) && value.every(isScalar))

export class BoundedLogAttributesProcessor implements LogRecordProcessor {
    constructor(private readonly delegate: LogRecordProcessor) {}

    onEmit(record: SdkLogRecord, context?: Context): void {
        const custom: Array<[string, AnyValue]> = []
        for (const [key, value] of Object.entries(record.attributes)) {
            if (flattenedKeys.has(key) && isFlatValue(value)) continue
            custom.push([key, value])
            delete record.attributes[key]
        }
        // Preserve an input named custom under its own key. It cannot replace
        // another attribute or the outer map, including via __proto__ keys.
        if (custom.length > 0)
            (record.attributes as LogAttributes).custom =
                Object.fromEntries(custom)
        this.delegate.onEmit(record, context)
    }

    forceFlush(): Promise<void> {
        return this.delegate.forceFlush()
    }

    shutdown(): Promise<void> {
        return this.delegate.shutdown()
    }
}
