import type {
    AgentConnectionInfo,
    AgentFramework
} from '@manyfold/shared'
import { Inject, Injectable, Logger } from '@nestjs/common'
import { eq } from 'drizzle-orm'
import {
    execSprite,
    type SpritesClient,
    type SpritesLogger
} from '@manyfold/sprites'
import { agents, jsonbMerge, type Database } from '@manyfold/db'
import { DRIZZLE } from '@/db/tokens'
import { ConnectionsService } from '@/modules/connections/connections.service'

// Bump when the AGENTS.manyfold.md layout changes so the platform/agent can
// detect an old doc and force a regenerate.
export const MANYFOLD_CONTEXT_VERSION = 1
export const MANYFOLD_CONTEXT_START = '<!-- manyfold-context-start -->'
export const MANYFOLD_CONTEXT_END = '<!-- manyfold-context-end -->'
const CONTEXT_FILE = 'AGENTS.manyfold.md'

// Coding frameworks whose instruction file auto-loads from the workspace root,
// and the file the reference block goes into. Service frameworks get nothing.
const INSTRUCTION_FILE: Partial<Record<AgentFramework, string>> = {
    'claude-code': 'CLAUDE.md',
    codex: 'AGENTS.md',
    'gemini-cli': 'GEMINI.md'
}

// The context doc only applies to coding frameworks on a workspace-root cwd.
export const contextDocInstructionFile = (
    framework: AgentFramework
): string | undefined => INSTRUCTION_FILE[framework]

const PROVIDER_LABEL: Record<string, string> = {
    github: 'GitHub',
    cloudflare: 'Cloudflare',
    composio: 'Composio'
}

const shellSingleQuote = (v: string): string =>
    `'${v.replace(/'/g, `'\\''`)}'`

export const buildPlatformContextDoc = (input: {
    agentId: string
    connections: AgentConnectionInfo[]
    generatedAt: string
}): string => {
    const lines = input.connections.length
        ? input.connections.map((c) => {
              const label = PROVIDER_LABEL[c.provider] ?? c.provider
              const account = c.account ? ` (${c.account})` : ''
              return `- **${label}**${account} — ${c.usage}`
          })
        : ['No connections are linked to this agent.']
    return [
        '---',
        `manyfold_context_version: ${MANYFOLD_CONTEXT_VERSION}`,
        `generated_at: ${input.generatedAt}`,
        `agent_id: ${input.agentId}`,
        '---',
        '',
        '<!-- Generated by Manyfold — do not edit; this file is overwritten. -->',
        '',
        '# Manyfold platform context',
        '',
        '## Connections',
        '',
        ...lines,
        '',
        'Run `mf connections` for full, live detail.',
        ''
    ].join('\n')
}

// Claude Code + Gemini CLI natively @import; Codex has no import syntax, so it
// gets a directive to read the file (the agent opens it on instruction).
const referenceBody = (framework: AgentFramework): string =>
    framework === 'codex'
        ? `Read \`${CONTEXT_FILE}\` (in this directory) for your Manyfold platform context — the connections linked to this agent and how to use them — before starting.`
        : `@${CONTEXT_FILE}`

export const buildReferenceBlock = (framework: AgentFramework): string =>
    [
        MANYFOLD_CONTEXT_START,
        referenceBody(framework),
        MANYFOLD_CONTEXT_END
    ].join('\n')

const buildContextScript = (input: {
    workspacePath: string
    instructionFile: string
    doc: string
    block: string
}): string =>
    [
        'set -eu',
        `WORKSPACE=${shellSingleQuote(input.workspacePath)}`,
        'mkdir -p "$WORKSPACE"',
        `DOC="$(cat <<'MF_CTX_DOC'\n${input.doc}\nMF_CTX_DOC\n)"`,
        `BLOCK="$(cat <<'MF_CTX_BLOCK'\n${input.block}\nMF_CTX_BLOCK\n)"`,
        `printf '%s\\n' "$DOC" > "$WORKSPACE/${CONTEXT_FILE}"`,
        `TARGET="$WORKSPACE/${input.instructionFile}"`,
        'touch "$TARGET"',
        // Idempotent: strip any prior managed block, then append the fresh one.
        // The user's own content outside the sentinels is preserved.
        `sed -i.bak '/${MANYFOLD_CONTEXT_START}/,/${MANYFOLD_CONTEXT_END}/d' "$TARGET" 2>/dev/null || true`,
        'rm -f "$TARGET.bak" 2>/dev/null || true',
        `printf '\\n%s\\n' "$BLOCK" >> "$TARGET"`,
        'echo MF_CTX_OK'
    ].join('\n')

// One exec seam per runtime kind: the script is plain bash either way, so the
// sprite path wraps execSprite and the daemon path wraps the daemon exec RPC.
export type ContextDocRunner = (
    script: string,
    timeoutMs: number
) => Promise<{ exitCode: number; stdout: string; stderr: string }>

export const spriteContextDocRunner = (
    client: SpritesClient,
    spriteName: string,
    logger?: SpritesLogger
): ContextDocRunner => async (script, timeoutMs) =>
    execSprite(
        client,
        spriteName,
        { cmd: ['bash', '-lc', script], stdin: '', timeoutMs },
        logger
    )

@Injectable()
export class AgentContextDocService {
    private readonly log = new Logger(AgentContextDocService.name)

    constructor(
        @Inject(DRIZZLE) private readonly db: Database,
        private readonly connections: ConnectionsService
    ) {}

    // Best-effort: write AGENTS.manyfold.md + the framework reference block into
    // the agent's workspace. A failure only makes the pushed summary stale —
    // `mf connections` remains the live source — so it never throws.
    async write(input: {
        agentId: string
        framework: AgentFramework
        workspacePath: string
        run: ContextDocRunner
        targetLabel: string
        timeoutMs?: number
    }): Promise<void> {
        const instructionFile = INSTRUCTION_FILE[input.framework]
        if (!instructionFile) return
        try {
            const generatedAt = new Date().toISOString()
            const connections =
                await this.connections.resolveAgentConnectionsById(
                    input.agentId
                )
            const script = buildContextScript({
                workspacePath: input.workspacePath,
                instructionFile,
                doc: buildPlatformContextDoc({
                    agentId: input.agentId,
                    connections,
                    generatedAt
                }),
                block: buildReferenceBlock(input.framework)
            })
            const result = await input.run(script, input.timeoutMs ?? 30_000)
            if (result.exitCode !== 0 || !result.stdout.includes('MF_CTX_OK')) {
                this.log.warn(
                    `context doc write failed on ${input.targetLabel}: ` +
                        `exit=${result.exitCode} stderr=${result.stderr.slice(0, 256)}`
                )
                return
            }
            // Record the installed version so the agent-detail card reports state
            // straight from the DB — no need to wake a cold runtime to read it.
            await this.db
                .update(agents)
                .set({
                    extras: jsonbMerge(agents.extras, {
                        contextDoc: {
                            version: MANYFOLD_CONTEXT_VERSION,
                            generatedAt
                        }
                    })
                })
                .where(eq(agents.id, input.agentId))
        } catch (err) {
            this.log.warn(
                `context doc write errored for ${input.agentId}: ${(err as Error).message}`
            )
        }
    }
}
